language: php

install:
  - travis_retry composer install --no-interaction --prefer-source

php:
  - 5.5
  - 5.6

script: phpunit --configuration ./phpunit.xml

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email: false
